# Generated by Django 5.0.4 on 2024-08-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camp', '0002_campfacility'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camp_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('camp_type', models.CharField(choices=[('Adventure', 'Adventure'), ('Luxury', 'Luxury'), ('Family', 'Family'), ('Eco', 'Eco')], max_length=50)),
                ('operating_hours', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('pricing_info', models.TextField(blank=True, null=True)),
                ('social_media_facebook', models.URLField(blank=True, null=True)),
                ('social_media_twitter', models.URLField(blank=True, null=True)),
                ('social_media_instagram', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
