# Generated by Django 5.0.4 on 2024-08-28 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camp', '0003_campprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='campprofile',
            name='camp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CampProfile', to='Camp.camp'),
            preserve_default=False,
        ),
    ]
