# Generated by Django 5.0.4 on 2024-08-28 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camp', '0004_campprofile_camp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campprofile',
            name='camp_type',
            field=models.CharField(choices=[('Adventure', 'Adventure'), ('Luxury', 'Luxury'), ('Family', 'Family'), ('Eco', 'Eco'), ('Friends', 'Friends')], max_length=50),
        ),
        migrations.CreateModel(
            name='CampImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='camp_images/')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Camp.campprofile')),
            ],
        ),
    ]
