# Generated by Django 5.0.4 on 2024-08-28 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camp', '0005_alter_campprofile_camp_type_campimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campimage',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Camp.camp'),
        ),
    ]
