# Generated by Django 5.0.4 on 2024-08-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Camp', '0007_camppackage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CampPackage',
        ),
    ]
