# Generated by Django 5.0.4 on 2024-08-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camp', '0009_camppackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='camppackage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
    ]
