# Generated by Django 5.0.4 on 2024-08-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camp', '0010_camppackage_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='vstatus',
            field=models.IntegerField(default=0),
        ),
    ]
