# Generated by Django 5.0.4 on 2024-08-31 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='total_price',
        ),
    ]
