# Generated by Django 5.0.4 on 2024-09-01 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Camp', '0011_camp_vstatus'),
        ('User', '0005_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='camp',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='Camp.camp'),
            preserve_default=False,
        ),
    ]
