# Generated by Django 5.0.4 on 2024-09-01 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_feedback_camp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='camp',
            new_name='camp_data',
        ),
    ]
