# Generated by Django 5.0.4 on 2024-09-01 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_rename_camp_feedback_camp_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='camp_data',
        ),
    ]
