# Generated by Django 5.0.4 on 2024-09-01 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_remove_feedback_camp_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
